# -----------------------------------------------------------------------------
# Image Release Information
# -----------------------------------------------------------------------------

# Image base name
IMAGE_BASENAME ?= "rpi-demo-base-image"

# Project name
IMAGE_PROJECT ?= "Yocto Raspberry Pi Mender Demo"

# Product release line (e.g. default, release-1.0, customized-xxx)
IMAGE_RELEASE ?= "default"

# Unique build identifier (e.g. local, Git commit, Git tag, CI build number)
IMAGE_BUILD_ID ?= "a13c8f2"

# Short description of this build, similar to a Git commit message (-m)
IMAGE_COMMENT ?= "First version"

# Mender Artifact Name
MENDER_ARTIFACT_NAME ?= "${IMAGE_BASENAME}-${IMAGE_RELEASE}-${IMAGE_BUILD_ID}"
